books/urls.py
from django.urls import path
from .views import listing, detail

app_name = 'books'
urlpatterns = [
    path('listing', listing, name='listing'),
    path('detail/<slug>', detail, name='detail'),
]

learningdjango/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenges/', include("challenges.urls")),
    path('books/', include("books.urls", namespace='books')),
    path('reviews/', include("reviews.urls", namespace='reviews')),
    path('filesuploader/', include("filesuploader.urls", namespace='filesuploader')),
    path('', lambda r: redirect("all-challenges")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from .views import review, feedback, ReviewView, ThankYouView, FeedbackListView, FeedbackDetailView, ReviewFormView, \
    FeedbackCreateView, SessionFavFeedback

app_name = 'reviews'

urlpatterns = [
    path('', review, name='add-review'),
    path('class-based-view-review', ReviewView.as_view(), name='add-class-based-view-review'),
    path('form-view-review', ReviewFormView.as_view(), name='add-form-view-review'),
    path('feedback', feedback, name='add-feedback'),
    path('create-view-feedback', FeedbackCreateView.as_view(), name='add-create-view-feedback'),
    path('thank-you', ThankYouView.as_view(), name='thank-you'),
    path('list-feedbacks', FeedbackListView.as_view(), name='list-feedbacks'),
    path('feedback-detail/<int:pk>', FeedbackDetailView.as_view(), name='feedback-detail'),
    path('session-fav-feedback/<int:pk>', SessionFavFeedback.as_view(), name='session-fav-feedback'),
]

reviews/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Feedback(models.Model):
    user_name = models.CharField(max_length=80)
    email = models.EmailField()
    comment = models.TextField()

    def get_absolute_url(self):
        return reverse('reviews:feedback-detail', args=[self.id])

reviews/forms.py
from django import forms
from reviews.models import Feedback


class ReviewForm(forms.Form):
    user_name = forms.CharField(label='Enter Your name', required=True, max_length=100, error_messages={
        'required': 'Your name must not be empty',
        'max_length': 'Please enter a shorter name'
    })
    email = forms.EmailField()
    comment = forms.CharField()


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'  # Selecting all fields
        # fields = ['user_name', 'comment']  # select some fields
        # exclude = ['excluded_field']  # exclude some fields
        labels = {
            'user_name': 'Enter Your Name'
        }
        error_messages = {
            'user_name': {
                'required': 'Your name must not be empty '
            }
        }

reviews/views.py
from django.db.models.functions import Length
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from .forms import ReviewForm, FeedbackForm
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView
from .models import Feedback


class ReviewView(View):
    def get(self, request):
        form = ReviewForm()
        return render(request, 'reviews/review.html', {"form": form})

    def post(self, request):
        form = ReviewForm(request.POST)
        if form.is_valid():
            # send email
            return redirect('reviews:thank-you')

        return render(request, 'reviews/review.html', {"form": form})


class ReviewFormView(FormView):
    form_class = ReviewForm
    template_name = 'reviews/review.html'
    success_url = reverse_lazy('reviews:thank-you')

    def form_valid(self, form):
        # send email
        return super(ReviewFormView, self).form_valid(form)


# Create your views here.
def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            # send email
            return redirect('reviews:thank-you')
    else:
        form = ReviewForm()
    return render(request, 'reviews/review.html', {"form": form})


def feedback(request):
    if request.method == 'POST':
        feedback_form = FeedbackForm(request.POST)
        if feedback_form.is_valid():
            feedback_form.save()
            return redirect('reviews:thank-you')
    else:
        feedback_form = FeedbackForm()
    return render(request, 'reviews/feedback.html', {"form": feedback_form})


class FeedbackCreateView(CreateView):
    model = Feedback
    fields = '__all__'

    template_name = 'reviews/feedback.html'
    success_url = reverse_lazy('reviews:thank-you')


class ThankYouView(TemplateView):
    template_name = 'reviews/thank-you.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_name"] = "Dear Customer"
        return context


class FeedbackListView(ListView):
    model = Feedback
    template_name = 'reviews/feedback_list.html'
    context_object_name = 'feedbacks'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FeedbackListView, self).get_context_data()
        context["session_favourite_review"] = self.request.session.get("session_favourite_review")
        return context

    def get_queryset(self):
        query_set = super(FeedbackListView, self).get_queryset()
        # returns only usernames more than 2
        return query_set.annotate(user_name_len=Length('user_name')).filter(user_name_len__gt=2)


class FeedbackDetailView(DetailView):
    model = Feedback
    template_name = 'reviews/feedback_detail.html'

    def get_context_data(self, **kwargs):
        context = super(FeedbackDetailView, self).get_context_data(**kwargs)
        context["is_session_favourite"] = self.request.session.get("session_favourite_review") == self.object.pk
        return context





class SessionFavFeedback(View):
    def post(self, request, pk):
        request.session["session_favourite_review"] = pk
        return redirect('reviews:feedback-detail', pk=pk)

reviews/templates/reviews/feedback.html
{% extends 'base.html' %}
{% block page_title %}
    Review
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for inp in form %}
            <div>
                {{ inp.label_tag }}
                <br>
                {{ inp }}
                <br>
                {{ inp.errors }}
                <br>
            </div>

        {% endfor %}


        <button>Send</button>
    </form>
{% endblock %}

reviews/templates/reviews/feedback_detail.html
{% extends 'base.html' %}
{% block page_title %}
    Feedback Detail
{% endblock %}
{% block content %}
    <div>
        <h4>Feedback from {{ feedback.email }}</h4>
        <h5>Name : {{ feedback.user_name }}</h5>

        <p>{{ feedback.comment }}</p>
        {% if is_session_favourite %}
            <span class="badge bg-danger">session Favourite</span>
        {% else %}
            <form action="{% url 'reviews:session-fav-feedback' feedback.pk %}" method="post">
                {% csrf_token %}
                <button class="btn btn-primary">Mark as session favourite</button>
            </form>
        {% endif %}
    </div>

    <hr>
    <div>
        <a class="btn btn-success" href="{% url 'reviews:list-feedbacks' %}">Show All feedbacks</a>
    </div>

{% endblock %}

reviews/templates/reviews/feedback_list.html
{% extends 'base.html' %}
{% block page_title %}
    Feedback List
{% endblock %}
{% block content %}
    <div><h4>Feedbacks from real names :</h4></div>
    <div class="row">
        <div class="col-6 fw-bolder">Comment</div>
        <div class="col-6 fw-bolder"> Username</div>
        {% for feedback in feedbacks %}
            <div class="col-6">
                <a href="{{ feedback.get_absolute_url }}">{{ feedback.comment }}</a>
                {% if feedback.pk == session_favourite_review %}
                    <span class="badge bg-danger">session Favourite</span>
                {% endif %}
            </div>
            <div class="col-6"> {{ feedback.user_name }}</div>
        {% endfor %}
    </div>
    <hr>
    <div>
        <a class="btn btn-secondary" href="{% url 'reviews:add-feedback' %}">Add feedback</a>
    </div>

{% endblock %}

reviews/templates/reviews/review.html
{% extends 'base.html' %}
{% block page_title %}
    Review
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}

        {% for inp in form %}
            <div>
                {{ inp.label_tag }}
                <br>
                {{ inp }}
                <br>
                {{ inp.errors }}
                <br>
            </div>

        {% endfor %}


        <button>Send</button>
    </form>
{% endblock %}

reviews/templates/reviews/thank-you.html
{% extends 'base.html' %}
{% block page_title %}
    Thank you
{% endblock %}
{% block content %}
    <br>
    <div class="alert alert-success">Review Completed successfully</div>
    <div>
        <h4>Thanks {{ user_name }}</h4>
        <p>We will send email to you</p>
        <a class="btn btn-primary" href="{% url 'reviews:add-review' %}">Add review</a>
        <a class="btn btn-secondary" href="{% url 'reviews:add-feedback' %}">Add feedback</a>
        <a class="btn btn-success" href="{% url 'reviews:list-feedbacks' %}">Show feedbacks</a>
    </div>
{% endblock %}